// mapping of possible team names to 3 letter team abbreviation
// assumes all key strings are entirely lowercase
exports.standardize = {
	"atlanta hawks" : "ATL",
	"hawks" : "ATL",
	"atlanta" : "ATL",
	"atl" : "ATL",
	"brooklyn nets" : "BKN",
	"nets" : "BKN",
	"brooklyn" : "BKN",
	"bkn" : "BKN",
	"boston celtics" : "BOS",
	"celtics" : "BOS",
	"boston" : "BOS",
	"bos" : "BOS",
	"charlotte hornets" : "CHA",
	"hornets" : "CHA",
	"charlotte" : "CHA",
	"cha" : "CHA",
	//charlotte bobcats?
	"chicago bulls" : "CHI",
	"bulls" : "CHI",
	"chicago" : "CHI",
	"chi" : "CHI",
	"cleveland cavaliers" : "CLE",
	"cavaliers" : "CLE",
	"cavs" : "CLE",
	"cleveland" : "CLE",
	"cle" : "CLE",
	"dallas mavericks" : "DAL",
	"mavericks" : "DAL",
	"mavs" : "DAL",
	"dallas" : "DAL",
	"dal" : "DAL",
	"denver nuggets" : "DEN",
	"nuggets" : "DEN",
	"nugs" : "DEN",
	"denver" : "DEN",
	"den" : "DEN",
	"detroit pistons" : "DET",
	"pistons" : "DET",
	"detroit" : "DET",
	"det" : "DET",
	"golden state warriors" : "GSW",
	"warriors" : "GSW",
	"golden state" : "GSW",
	"gsw" : "GSW",
	"houston rockets" : "HOU",
	"rockets" : "HOU",
	"houston" : "HOU",
	"hou" : "HOU",
	"indiana pacers" : "IND",
	"pacers" : "IND",
	"indiana" : "IND",
	"ind" : "IND",
	"los angeles clippers" : "LAC",
	"clippers" : "LAC",
	"la clippers" : "LAC",
	"l a clippers" : "LAC",
	"lac" : "LAC",
	"los angeles lakers" : "LAL",
	"la lakers" : "LAL",
	"l a lakers" : "LAL",
	"lakers" : "LAL",
	"lal" : "LAL",
	"memphis grizzlies" : "MEM",
	"grizzlies" : "MEM",
	"memphis" : "MEM",
	"mem" : "MEM",
	"miami heat" : "MIA",
	"heat" : "MIA",
	"miami" : "MIA",
	"mia" : "MIA",
	"milwaukee bucks" : "MIL",
	"bucks" : "MIL",
	"milwaukee" : "MIL",
	"mil" : "MIL",
	"minnesota timberwolves" : "MIN",
	"timerwolves" : "MIN",
	"minnesota" : "MIN",
	"min" : "MIN",
	"new orleans pelicans" : "NOP",
	"pelicans" : "NOP",
	"n o pelicans" : "NOP",
	"no pelicans" : "NOP",
	"new orleans" : "NOP",
	"nop" : "NOP",
	//new orleans hornets/okc hornets?
	"new york knicks" : "NYK",
	"ny knicks" : "NYK",
	"n y knicks" : "NYK",
	"knicks" : "NYK",
	"new york" : "NYK",
	"ny" : "NYK",
	"n y" : "NYK",
	"nyk" : "NYK",
	"oklahoma city thunder" : "OKC",
	"oklahoma city" : "OKC",
	"okc thunder" : "OKC",
	"thunder" : "OKC",
	"okc" : "OKC",
	//seattle supersonics?
	"orlando magic" : "ORL",
	"magic" : "ORL",
	"orlando" : "ORL",
	"orl" : "ORL",
	"philadelphia 76ers" : "PHI",
	"76ers" : "PHI",
	"philadelphia" : "PHI",
	"phi" : "PHI",
	"phoenix suns" : "PHX",
	"suns" : "PHX",
	"phoenix" : "PHX",
	"phx" : "PHX",
	"portland trail blazers" : "POR",
	"trail blazers" : "POR",
	"blazers" : "POR",
	"portland" : "POR",
	"por" : "POR",
	"sacramento kings" : "SAC",
	"kings" : "SAC",
	"sacramento" : "SAC",
	"sac" : "SAC",
	"san antonio spurs" : "SAS",
	"spurs" : "SAS",
	"sa spurs" : "SAS",
	"s a spurs" : "SAS",
	"san antonio" : "SAS",
	"sas" : "SAS",
	"toronto raptors" : "TOR",
	"raptors" : "TOR",
	"toronto" : "TOR",
	"tor" : "TOR",
	"utah jazz" : "UTA",
	"jazz" : "UTA",
	"utah" : "UTA",
	"uta" : "UTA",
	"washington wizards" : "WAS",
	"wizards" : "WAS",
	"washington" : "WAS",
	"was" : "WAS"
}